### ISSUE TITLE
Adicionar email dos membros da comissão

### ISSUE THREAD

**Issue by viguardieiro** [CEPLN/cepln.github.io#3]

**Comment by arademaker** [comment]
Também precisamos adicionar os membros da comissão atual (vide e-mail hoje os destinatários no campo PARA)

**Comment by arademaker** [comment]
podemos manter a página comissão como está agora, não acho necessário acrescentar emails. Os membros podem pedir para colocar links para suas homepages. Se eles fornecerem, colocamos.
